# Generated by Django 6.0.3 on 2026-09-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=150)),
                ('vin_number', models.CharField(blank=True, help_text='17-character Vehicle Identification Number', max_length=17)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_year', models.PositiveIntegerField()),
                ('engine_details', models.CharField(blank=True, help_text='Example: 1.6 petrol, 2.0 TDI, 1.4 TSI', max_length=100)),
                ('part_name', models.CharField(max_length=200)),
                ('part_description', models.TextField(blank=True, help_text='Describe the part or problem')),
                ('part_image', models.ImageField(blank=True, help_text='Upload a photo of the part if available', null=True, upload_to='part_requests/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
