# Generated by Django 6.0.3 on 2026-09-07 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.CharField(blank=True, help_text='Example: In stock, 2 days, Order required', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional information about the quote')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.partrequest')),
            ],
        ),
    ]
