# Generated by Django 6.0.3 on 2026-09-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='shop_phone',
            field=models.CharField(default='0712345678', max_length=20),
            preserve_default=False,
        ),
    ]
