# Generated by Django 6.0.3 on 2026-09-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_shop_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
