# Generated by Django 6.0.3 on 2026-09-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_partrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
