# Generated by Django 6.0.3 on 2026-09-08 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.shop'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='shop_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='quote',
            name='shop_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
