# Generated by Django 6.0.3 on 2026-09-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_quote_shop_alter_quote_shop_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('part_request', 'shop'), name='unique_shop_quote_per_request'),
        ),
    ]
