# Generated by Django 6.0.3 on 2026-09-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_quote_unique_shop_quote_per_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
