# Generated by Django 6.0.3 on 2026-09-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_alter_partrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='request_round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
