# Generated by Django 6.0.3 on 2026-09-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_partrequest_request_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
