# Generated by Django 6.0.3 on 2026-09-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_quote_quote_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='public_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
