# Generated by Django 6.0.3 on 2026-09-08 12:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_partrequest_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partrequest',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
