# Generated by Django 6.0.3 on 2026-09-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_alter_partrequest_public_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(condition=models.Q(('is_accepted', True)), fields=('part_request',), name='one_accepted_quote_per_request'),
        ),
    ]
