# Generated by Django 6.0.3 on 2026-09-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='marketplace_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='private_qr_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
