# Generated by Django 6.0.3 on 2026-09-10 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0016_shop_marketplace_enabled_shop_private_qr_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='request_source',
            field=models.CharField(choices=[('marketplace', 'Marketplace'), ('mechanic_qr', 'Mechanic QR'), ('shop_qr', 'Shop QR')], default='marketplace', max_length=20),
        ),
        migrations.AddField(
            model_name='partrequest',
            name='source_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_requests', to='quotes.shop'),
        ),
    ]
