# Generated by Django 6.0.3 on 2026-09-10 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0018_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='quotes.notification')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to='quotes.shop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('notification', 'shop'), name='unique_notification_read_per_shop')],
            },
        ),
    ]
