# Generated by Django 6.0.3 on 2026-09-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0019_notificationread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
