# Generated by Django 6.0.3 on 2026-09-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0021_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='licence_disc_image',
            field=models.ImageField(blank=True, help_text='Upload a clear photo of the vehicle licence disc', null=True, upload_to='licence_discs/'),
        ),
        migrations.AddField(
            model_name='partrequest',
            name='vehicle_input_method',
            field=models.CharField(choices=[('manual', 'Enter Vehicle Details'), ('disc', 'Upload Licence Disc')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='partrequest',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='partrequest',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='partrequest',
            name='vehicle_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
